import type { PhoneNumberType } from "../types/utils/constants.types.ts";

export const phoneNumbers: PhoneNumberType[] = [
  {
    countryName: "Afghanistan",
    placeholder: "+93",
    pattern: "^\\+93\\d{7,12}$",
    countryFlag: "🇦🇫",
  },
  {
    countryName: "Albania",
    placeholder: "+355",
    pattern: "^\\+355\\d{7,12}$",
    countryFlag: "🇦🇱",
  },
  {
    countryName: "Algeria",
    placeholder: "+213",
    pattern: "^\\+213\\d{7,12}$",
    countryFlag: "🇩🇿",
  },
  {
    countryName: "Andorra",
    placeholder: "+376",
    pattern: "^\\+376\\d{7,12}$",
    countryFlag: "🇦🇩",
  },
  {
    countryName: "Angola",
    placeholder: "+244",
    pattern: "^\\+244\\d{7,12}$",
    countryFlag: "🇦🇴",
  },
  {
    countryName: "Antigua and Barbuda",
    placeholder: "+1268",
    pattern: "^\\+1268\\d{7,12}$",
    countryFlag: "🇦🇬",
  },
  {
    countryName: "Argentina",
    placeholder: "+54",
    pattern: "^\\+54\\d{7,12}$",
    countryFlag: "🇦🇷",
  },
  {
    countryName: "Armenia",
    placeholder: "+374",
    pattern: "^\\+374\\d{7,12}$",
    countryFlag: "🇦🇲",
  },
  {
    countryName: "Australia",
    placeholder: "+61",
    pattern: "^\\+61\\d{7,12}$",
    countryFlag: "🇦🇺",
  },
  {
    countryName: "Austria",
    placeholder: "+43",
    pattern: "^\\+43\\d{7,12}$",
    countryFlag: "🇦🇹",
  },
  {
    countryName: "Azerbaijan",
    placeholder: "+994",
    pattern: "^\\+994\\d{7,12}$",
    countryFlag: "🇦🇿",
  },
  {
    countryName: "Bahamas",
    placeholder: "+1242",
    pattern: "^\\+1242\\d{7,12}$",
    countryFlag: "🇧🇸",
  },
  {
    countryName: "Bahrain",
    placeholder: "+973",
    pattern: "^\\+973\\d{7,12}$",
    countryFlag: "🇧🇭",
  },
  {
    countryName: "Bangladesh",
    placeholder: "+880",
    pattern: "^\\+880\\d{7,12}$",
    countryFlag: "🇧🇩",
  },
  {
    countryName: "Barbados",
    placeholder: "+1246",
    pattern: "^\\+1246\\d{7,12}$",
    countryFlag: "🇧🇧",
  },
  {
    countryName: "Belarus",
    placeholder: "+375",
    pattern: "^\\+375\\d{7,12}$",
    countryFlag: "🇧🇾",
  },
  {
    countryName: "Belgium",
    placeholder: "+32",
    pattern: "^\\+32\\d{7,12}$",
    countryFlag: "🇧🇪",
  },
  {
    countryName: "Belize",
    placeholder: "+501",
    pattern: "^\\+501\\d{7,12}$",
    countryFlag: "🇧🇿",
  },
  {
    countryName: "Benin",
    placeholder: "+229",
    pattern: "^\\+229\\d{7,12}$",
    countryFlag: "🇧🇯",
  },
  {
    countryName: "Bhutan",
    placeholder: "+975",
    pattern: "^\\+975\\d{7,12}$",
    countryFlag: "🇧🇹",
  },
  {
    countryName: "Bolivia",
    placeholder: "+591",
    pattern: "^\\+591\\d{7,12}$",
    countryFlag: "🇧🇴",
  },
  {
    countryName: "Bosnia and Herzegovina",
    placeholder: "+387",
    pattern: "^\\+387\\d{7,12}$",
    countryFlag: "🇧🇦",
  },
  {
    countryName: "Botswana",
    placeholder: "+267",
    pattern: "^\\+267\\d{7,12}$",
    countryFlag: "🇧🇼",
  },
  {
    countryName: "Brazil",
    placeholder: "+55",
    pattern: "^\\+55\\d{7,12}$",
    countryFlag: "🇧🇷",
  },
  {
    countryName: "Brunei",
    placeholder: "+673",
    pattern: "^\\+673\\d{7,12}$",
    countryFlag: "🇧🇳",
  },
  {
    countryName: "Bulgaria",
    placeholder: "+359",
    pattern: "^\\+359\\d{7,12}$",
    countryFlag: "🇧🇬",
  },
  {
    countryName: "Burkina Faso",
    placeholder: "+226",
    pattern: "^\\+226\\d{7,12}$",
    countryFlag: "🇧🇫",
  },
  {
    countryName: "Burundi",
    placeholder: "+257",
    pattern: "^\\+257\\d{7,12}$",
    countryFlag: "🇧🇮",
  },
  {
    countryName: "Cambodia",
    placeholder: "+855",
    pattern: "^\\+855\\d{7,12}$",
    countryFlag: "🇰🇭",
  },
  {
    countryName: "Cameroon",
    placeholder: "+237",
    pattern: "^\\+237\\d{7,12}$",
    countryFlag: "🇨🇲",
  },
  {
    countryName: "Canada",
    placeholder: "+1",
    pattern: "^\\+1\\d{7,12}$",
    countryFlag: "🇨🇦",
  },
  {
    countryName: "Cape Verde",
    placeholder: "+238",
    pattern: "^\\+238\\d{7,12}$",
    countryFlag: "🇨🇻",
  },
  {
    countryName: "Central African Republic",
    placeholder: "+236",
    pattern: "^\\+236\\d{7,12}$",
    countryFlag: "🇨🇫",
  },
  {
    countryName: "Chad",
    placeholder: "+235",
    pattern: "^\\+235\\d{7,12}$",
    countryFlag: "🇹🇩",
  },
  {
    countryName: "Chile",
    placeholder: "+56",
    pattern: "^\\+56\\d{7,12}$",
    countryFlag: "🇨🇱",
  },
  {
    countryName: "China",
    placeholder: "+86",
    pattern: "^\\+86\\d{7,12}$",
    countryFlag: "🇨🇳",
  },
  {
    countryName: "Colombia",
    placeholder: "+57",
    pattern: "^\\+57\\d{7,12}$",
    countryFlag: "🇨🇴",
  },
  {
    countryName: "Comoros",
    placeholder: "+269",
    pattern: "^\\+269\\d{7,12}$",
    countryFlag: "🇰🇲",
  },
  {
    countryName: "Congo (Republic)",
    placeholder: "+242",
    pattern: "^\\+242\\d{7,12}$",
    countryFlag: "🇨🇬",
  },
  {
    countryName: "Congo (Democratic Republic)",
    placeholder: "+243",
    pattern: "^\\+243\\d{7,12}$",
    countryFlag: "🇨🇩",
  },
  {
    countryName: "Costa Rica",
    placeholder: "+506",
    pattern: "^\\+506\\d{7,12}$",
    countryFlag: "🇨🇷",
  },
  {
    countryName: "Croatia",
    placeholder: "+385",
    pattern: "^\\+385\\d{7,12}$",
    countryFlag: "🇭🇷",
  },
  {
    countryName: "Cuba",
    placeholder: "+53",
    pattern: "^\\+53\\d{7,12}$",
    countryFlag: "🇨🇺",
  },
  {
    countryName: "Cyprus",
    placeholder: "+357",
    pattern: "^\\+357\\d{7,12}$",
    countryFlag: "🇨🇾",
  },
  {
    countryName: "Czech Republic",
    placeholder: "+420",
    pattern: "^\\+420\\d{7,12}$",
    countryFlag: "🇨🇿",
  },
  {
    countryName: "Denmark",
    placeholder: "+45",
    pattern: "^\\+45\\d{7,12}$",
    countryFlag: "🇩🇰",
  },
];
