// Social account enum type
export type TSocialAccounts =
  | "instagram"
  | "tiktok"
  | "facebook"
  | "youtube"
  | "spotify"
  | "soundcloud"
  | "press";

// Social account draft type for create/edit(update) forms
export type CountryItem = { country: string | null; percentage: number | null };
export type MusicGenreItem = { genre: string; subGenres: string[] };
export type ProfileCategory = "community" | "creator";
export type ProfileCurrency = "EUR";

export type SocialAccountDraft = {
  // id optional for draft (id will be generated by backend API, index used in UI)
  accountId?: string;

  username: string;
  profileLink: string;
  followers: number | null;
  logoUrl: string;
  profileCategory: ProfileCategory;
  price: number | null;
  currency: ProfileCurrency;
  musicGenres: MusicGenreItem[];
  categories: string[];
  creatorCategories: string[];
  countries: CountryItem[];
};

// Short social account type for lists and overviews
export type TSocialAccountShort = {
  accountId?: string;
  username: string;
};

// Signup draft type
export interface ISignupInfluencerDraft {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  password: string;

  instagram: SocialAccountDraft[];
  tiktok: SocialAccountDraft[];
  youtube: SocialAccountDraft[];
  facebook: SocialAccountDraft[];
  spotify: SocialAccountDraft[];
  soundcloud: SocialAccountDraft[];
  press: SocialAccountDraft[];
}

// Influencer profile type from API
export interface InfluencerProfileApi {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  profilePhotoUrl?: string;
  telegramUsername?: string;

  instagram: TSocialAccountShort[];
  tiktok: TSocialAccountShort[];
  youtube: TSocialAccountShort[];
  facebook: TSocialAccountShort[];
  spotify: TSocialAccountShort[];
  soundcloud: TSocialAccountShort[];
  press: TSocialAccountShort[];
};

// Create social account DTO
export type TCreateSocialAccountDTO = SocialAccountDraft & { socialMedia: TSocialAccounts };

// Update social account DTO
export type TUpdateSocialAccountDTO = SocialAccountDraft & { accountId: string; socialMedia: TSocialAccounts };

// Delete social account DTO
export interface TDeleteSocialAccountDTO {
  accountId: string;
  socialMedia: TSocialAccounts;
  deleteReason: string;
};

// Influencer profile details types
export type TInfluencerProfileDetailsModel = Pick<InfluencerProfileApi,
  | "firstName"
  | "lastName"
  | "email"
  | "phone"
  | "profilePhotoUrl"
  | "telegramUsername"
>;

export type TInfluencerProfileUpdateModel = Partial<TInfluencerProfileDetailsModel>;